### PR TITLE
Fix num routers and router radix assumption in info logging

### LINKED ISSUE #5: Don't assume all routers have the same radix
https://github.com/ssnetsim/supersim/blob/11fc7a4c30b9bf8cb0a3450c8ace3fab1de398b9/src/main.cc#L63

This has the side-effect of crashing on a network with no routers (which is useful for testing).

### PR DESCRIPTION
**Pull request by nicmcd**
Fixes #5. Modified main.cc to read all router radices and print distribution. Will work with zero routers as well. Here is a sample output of a InfoLog:

```
Endpoints,60                                   
Routers,45                                                
Router radix 7,45                                   
VCs,1                                          
Components,3316                                      
Total event count,26937118 
Total sim units,55995000                       
Total real seconds,6.407172
Events per real second,4204213.457067              
Events per sim unit,0.481063                                
Sim units per real second,8739425.373141      
```     

bazel test :* passes all unit tests
./scripts/run_examples.py passes all checks

### CODE REVIEW

File: src/main.cc [hunk 1]
```diff
@@ -60,13 +60,19 @@ s32 main(s32 _argc, char** _argv) {
   gSim->setNetwork(network);
   u32 numInterfaces = network->numInterfaces();
   u32 numRouters = network->numRouters();
-  u32 routerRadix = network->getRouter(0)->numPorts();
+  std::map<u32, u32> routerRadices;
+  for (u32 routerId = 0; routerId < numRouters; routerId++) {
+    routerRadices[network->getRouter(0)->numPorts()] += 1;
```
Comment (knrafto) [inline src/main.cc]: 0 -> routerId

Comment (nicmcd) [reply src/main.cc]: Ha, good catch.

**Comment by nicmcd** [comment]
Sweeping through all routers found a bug in the dragonfly network. See 
e6e83e3. All unit tests and examples now pass.
